spring:
  application:
    name: step07_cicd
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: "prometheus,health,metrics"
  prometheus:
    metrics:
      export:
        enabled: true	
